# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- task: DockerCompose@0
  displayName: 'Test services'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker Hub'

    additionalDockerComposeFiles: 'docker-compose.override.yml'

    dockerComposeFileArgs: '$(Parameters.dockerComposeFileArgs)'

    action: 'Run services'


- task: DockerCompose@0
  displayName: 'Build services'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker Hub'

    additionalDockerComposeFiles: 'docker-compose.prod.yml'

    dockerComposeFileArgs: '$(Parameters.dockerComposeFileArgs)'

    action: 'Build services'


- task: DockerCompose@0
  displayName: 'Push services'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker Hub'

    additionalDockerComposeFiles: 'docker-compose.prod.yml'

    dockerComposeFileArgs: '$(Parameters.dockerComposeFileArgs)'

    action: 'Push services'

    includeSourceTags: true

    includeLatestTag: true
    
