resources:
- repo: self
queue:
  name: Hosted Linux Preview
#Your build pipeline references an undefined variable named ‘Parameters.dockerComposeFileArgs’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.dockerComposeFileArgs’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.dockerComposeFileArgs’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
steps:
- task: DockerCompose@0
  displayName: 'Test services'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker Hub'

    additionalDockerComposeFiles: 'docker-compose.test.yml'

    dockerComposeFileArgs: '$(Parameters.dockerComposeFileArgs)'

    dockerComposeCommand: 'up --abort-on-container-exit'


- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testRunner: VSTest

    testResultsFiles: '**/*.trx'

    mergeTestResults: true


- task: DockerCompose@0
  displayName: 'Build services'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker Hub'

    additionalDockerComposeFiles: 'docker-compose.prod.yml'

    dockerComposeFileArgs: '$(Parameters.dockerComposeFileArgs)'

    action: 'Build services'


- task: DockerCompose@0
  displayName: 'Push services'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker Hub'

    additionalDockerComposeFiles: 'docker-compose.prod.yml'

    dockerComposeFileArgs: '$(Parameters.dockerComposeFileArgs)'

    action: 'Push services'

    includeSourceTags: true

    includeLatestTag: true
