version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY}todoapi
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    links:
      - tododb
    depends_on:
      - tododb
  tododb:
    image: mongo
    volumes:
      - ./data:/data/db
      - "./mongo-createuser-entrypoint.sh:/docker-entrypoint-initdb.d/"
