version: '3.4'

services:
  todoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
  tododb:
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
