version: '3.4'

services:
  todo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
  todo.db:
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
