version: '3.4'

services:
  testdb:
    image: mongo
    environment:
      - TODO_MONGO_DB=TestDatabase
      - TODO_MONGO_USER=TestUser
      - TODO_MONGO_PASS=Secret
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  libraries:
    image: todoapi
    build:
      context: .
      dockerfile: Shared/Dockerfile
    links:
      - testdb
    depends_on:
      - testdb
  todoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
  tododb:
    ports:
      - "27018:27017"
