version: '3.4'

services:
  tododb:
    image: mongo
    environment:
      - TODO_MONGO_DB=${TODO_MONGO_DB}
      - TODO_MONGO_USER=${TODO_MONGO_USER}
      - TODO_MONGO_PASS=${TODO_MONGO_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  todoapi:
    image: ${DOCKER_REGISTRY}/todoapi
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    environment:
      - TODO_MONGO_HOST=${TODO_MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - TODO_MONGO_DB=${TODO_MONGO_DB}
      - TODO_MONGO_USER=${TODO_MONGO_USER}
      - TODO_MONGO_PASS=${TODO_MONGO_PASS}
    links:
      - tododb
    depends_on:
      - tododb
