version: '3.4'

services:
  testdb:
    image: mongo
    environment:
      - TODO_MONGO_DB=TestDatabase
      - TODO_MONGO_USER=TestUser
      - TODO_MONGO_PASS=Secret
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "27016:27017"
  libraries.tests:
    image: libraries
    build:
      context: .
      dockerfile: Shared.Tests/Dockerfile
    volumes:
      - ./Shared.Tests/TestResults:/src/Shared.Tests/TestResults
    links:
      - testdb
    depends_on:
      - testdb
  todo.tests:
    image: todotests
    build:
      context: .
      dockerfile: TodoApi.Tests/Dockerfile
    volumes:
      - ./TodoApi.Tests/TestResults:/src/TodoApi.Tests/TestResults
  todo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
  todo.db:
    ports:
      - "27018:27017"
